#pragma once

static const char DASHBOARD_HTML[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "    <meta charset=\"UTF-8\">\n"
    "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
    "    <title>netscope</title>\n"
    "    <style>\n"
    "        * { margin: 0; padding: 0; box-sizing: border-box; }\n"
    "\n"
    "        body {\n"
    "            background: #0a0e1a;\n"
    "            color: #e2e8f0;\n"
    "            font-family: 'Courier New', monospace;\n"
    "            height: 100vh;\n"
    "            display: flex;\n"
    "            flex-direction: column;\n"
    "            overflow: hidden;\n"
    "        }\n"
    "\n"
    "        /* ── Header ── */\n"
    "        header {\n"
    "            display: flex;\n"
    "            align-items: center;\n"
    "            justify-content: space-between;\n"
    "            padding: 12px 24px;\n"
    "            background: #0d1117;\n"
    "            border-bottom: 1px solid #1e2d3d;\n"
    "            flex-shrink: 0;\n"
    "        }\n"
    "\n"
    "        .logo {\n"
    "            font-size: 1.2rem;\n"
    "            font-weight: bold;\n"
    "            color: #38bdf8;\n"
    "            letter-spacing: 2px;\n"
    "        }\n"
    "\n"
    "        .logo span { color: #64748b; }\n"
    "\n"
    "        .status {\n"
    "            display: flex;\n"
    "            align-items: center;\n"
    "            gap: 8px;\n"
    "            font-size: 0.75rem;\n"
    "            color: #64748b;\n"
    "        }\n"
    "\n"
    "        .status-dot {\n"
    "            width: 8px;\n"
    "            height: 8px;\n"
    "            border-radius: 50%;\n"
    "            background: #ef4444;\n"
    "            transition: background 0.3s;\n"
    "        }\n"
    "\n"
    "        .status-dot.connected { background: #22c55e; }\n"
    "\n"
    "        /* ── Stats bar ── */\n"
    "        .stats-bar {\n"
    "            display: flex;\n"
    "            gap: 1px;\n"
    "            background: #1e2d3d;\n"
    "            flex-shrink: 0;\n"
    "        }\n"
    "\n"
    "        .stat {\n"
    "            flex: 1;\n"
    "            padding: 10px 16px;\n"
    "            background: #0d1117;\n"
    "            text-align: center;\n"
    "        }\n"
    "\n"
    "        .stat-value {\n"
    "            font-size: 1.4rem;\n"
    "            font-weight: bold;\n"
    "            color: #38bdf8;\n"
    "        }\n"
    "\n"
    "        .stat-label {\n"
    "            font-size: 0.65rem;\n"
    "            color: #64748b;\n"
    "            text-transform: uppercase;\n"
    "            letter-spacing: 1px;\n"
    "            margin-top: 2px;\n"
    "        }\n"
    "\n"
    "        /* ── Main layout ── */\n"
    "        .main {\n"
    "            display: grid;\n"
    "            grid-template-columns: 1fr 280px;\n"
    "            grid-template-rows: 200px 1fr;\n"
    "            gap: 1px;\n"
    "            background: #1e2d3d;\n"
    "            flex: 1;\n"
    "            overflow: hidden;\n"
    "        }\n"
    "\n"
    "        /* ── Chart area ── */\n"
    "        .chart-area {\n"
    "            background: #0d1117;\n"
    "            padding: 16px;\n"
    "            display: flex;\n"
    "            flex-direction: column;\n"
    "        }\n"
    "\n"
    "        .panel-title {\n"
    "            font-size: 0.7rem;\n"
    "            color: #64748b;\n"
    "            text-transform: uppercase;\n"
    "            letter-spacing: 1px;\n"
    "            margin-bottom: 12px;\n"
    "        }\n"
    "\n"
    "        canvas {\n"
    "            flex: 1;\n"
    "            width: 100%;\n"
    "        }\n"
    "\n"
    "        /* ── Protocol breakdown ── */\n"
    "        .protocol-panel {\n"
    "            background: #0d1117;\n"
    "            padding: 16px;\n"
    "            grid-row: 1 / 3;\n"
    "        }\n"
    "\n"
    "        .proto-bar {\n"
    "            margin-bottom: 12px;\n"
    "        }\n"
    "\n"
    "        .proto-header {\n"
    "            display: flex;\n"
    "            justify-content: space-between;\n"
    "            font-size: 0.75rem;\n"
    "            margin-bottom: 4px;\n"
    "        }\n"
    "\n"
    "        .proto-name { color: #e2e8f0; }\n"
    "        .proto-count { color: #64748b; }\n"
    "\n"
    "        .proto-track {\n"
    "            height: 4px;\n"
    "            background: #1e2d3d;\n"
    "            border-radius: 2px;\n"
    "            overflow: hidden;\n"
    "        }\n"
    "\n"
    "        .proto-fill {\n"
    "            height: 100%;\n"
    "            border-radius: 2px;\n"
    "            transition: width 0.5s ease;\n"
    "        }\n"
    "\n"
    "        .fill-tcp  { background: #38bdf8; }\n"
    "        .fill-udp  { background: #a78bfa; }\n"
    "        .fill-icmp { background: #fb923c; }\n"
    "        .fill-other{ background: #64748b; }\n"
    "\n"
    "        /* ── Packet feed ── */\n"
    "        .packet-feed {\n"
    "            background: #0d1117;\n"
    "            padding: 16px;\n"
    "            overflow: hidden;\n"
    "            display: flex;\n"
    "            flex-direction: column;\n"
    "        }\n"
    "\n"
    "        .feed-scroll {\n"
    "            flex: 1;\n"
    "            overflow-y: auto;\n"
    "            scrollbar-width: thin;\n"
    "            scrollbar-color: #1e2d3d transparent;\n"
    "        }\n"
    "\n"
    "        .packet-row {\n"
    "            display: grid;\n"
    "            grid-template-columns: 50px 70px 160px 20px 160px 60px 80px;\n"
    "            gap: 8px;\n"
    "            padding: 3px 0;\n"
    "            border-bottom: 1px solid #0a0e1a;\n"
    "            font-size: 0.72rem;\n"
    "            align-items: center;\n"
    "            animation: fadeIn 0.2s ease;\n"
    "        }\n"
    "\n"
    "        @keyframes fadeIn {\n"
    "            from { opacity: 0; transform: translateX(-4px); }\n"
    "            to   { opacity: 1; transform: translateX(0); }\n"
    "        }\n"
    "\n"
    "        .packet-row:hover { background: #0f172a; }\n"
    "\n"
    "        .col-num   { color: #334155; }\n"
    "        .col-proto { font-weight: bold; }\n"
    "        .col-tcp   { color: #38bdf8; }\n"
    "        .col-udp   { color: #a78bfa; }\n"
    "        .col-icmp  { color: #fb923c; }\n"
    "        .col-other { color: #64748b; }\n"
    "        .col-ip    { color: #94a3b8; }\n"
    "        .col-arrow { color: #334155; text-align: center; }\n"
    "        .col-bytes { color: #64748b; text-align: right; }\n"
    "        .col-svc   {\n"
    "            color: #22c55e;\n"
    "            font-size: 0.65rem;\n"
    "            background: #052e16;\n"
    "            padding: 1px 4px;\n"
    "            border-radius: 2px;\n"
    "            text-align: center;\n"
    "        }\n"
    "\n"
    "        .feed-header {\n"
    "            display: grid;\n"
    "            grid-template-columns: 50px 70px 160px 20px 160px 60px 80px;\n"
    "            gap: 8px;\n"
    "            padding: 0 0 6px 0;\n"
    "            border-bottom: 1px solid #1e2d3d;\n"
    "            font-size: 0.65rem;\n"
    "            color: #334155;\n"
    "            text-transform: uppercase;\n"
    "            letter-spacing: 1px;\n"
    "            margin-bottom: 4px;\n"
    "            flex-shrink: 0;\n"
    "        }\n"
    "    </style>\n"
    "</head>\n"
    "<body>\n"
    "\n"
    "<header>\n"
    "    <div class=\"logo\">net<span>scope</span></div>\n"
    "    <div class=\"status\">\n"
    "        <div class=\"status-dot\" id=\"statusDot\"></div>\n"
    "        <span id=\"statusText\">Connecting...</span>\n"
    "    </div>\n"
    "</header>\n"
    "\n"
    "<div class=\"stats-bar\">\n"
    "    <div class=\"stat\">\n"
    "        <div class=\"stat-value\" id=\"statTotal\">0</div>\n"
    "        <div class=\"stat-label\">Total Packets</div>\n"
    "    </div>\n"
    "    <div class=\"stat\">\n"
    "        <div class=\"stat-value\" id=\"statRate\">0</div>\n"
    "        <div class=\"stat-label\">Packets / sec</div>\n"
    "    </div>\n"
    "    <div class=\"stat\">\n"
    "        <div class=\"stat-value\" id=\"statBytes\">0</div>\n"
    "        <div class=\"stat-label\">KB / sec</div>\n"
    "    </div>\n"
    "    <div class=\"stat\">\n"
    "        <div class=\"stat-value\" id=\"statTCP\">0</div>\n"
    "        <div class=\"stat-label\">TCP</div>\n"
    "    </div>\n"
    "    <div class=\"stat\">\n"
    "        <div class=\"stat-value\" id=\"statUDP\">0</div>\n"
    "        <div class=\"stat-label\">UDP</div>\n"
    "    </div>\n"
    "    <div class=\"stat\">\n"
    "        <div class=\"stat-value\" id=\"statHosts\">0</div>\n"
    "        <div class=\"stat-label\">Unique Hosts</div>\n"
    "    </div>\n"
    "</div>\n"
    "\n"
    "<div class=\"main\">\n"
    "\n"
    "    <!-- Bandwidth chart -->\n"
    "    <div class=\"chart-area\">\n"
    "        <div class=\"panel-title\">Bandwidth (bytes/sec)</div>\n"
    "        <canvas id=\"bwChart\"></canvas>\n"
    "    </div>\n"
    "\n"
    "    <!-- Protocol breakdown -->\n"
    "    <div class=\"protocol-panel\">\n"
    "        <div class=\"panel-title\">Protocol Breakdown</div>\n"
    "        <div class=\"proto-bar\">\n"
    "            <div class=\"proto-header\">\n"
    "                <span class=\"proto-name\">TCP</span>\n"
    "                <span class=\"proto-count\" id=\"pTCP\">0</span>\n"
    "            </div>\n"
    "            <div class=\"proto-track\">\n"
    "                <div class=\"proto-fill fill-tcp\"\n"
    "                     id=\"bTCP\" style=\"width:0%\"></div>\n"
    "            </div>\n"
    "        </div>\n"
    "        <div class=\"proto-bar\">\n"
    "            <div class=\"proto-header\">\n"
    "                <span class=\"proto-name\">UDP</span>\n"
    "                <span class=\"proto-count\" id=\"pUDP\">0</span>\n"
    "            </div>\n"
    "            <div class=\"proto-track\">\n"
    "                <div class=\"proto-fill fill-udp\"\n"
    "                     id=\"bUDP\" style=\"width:0%\"></div>\n"
    "            </div>\n"
    "        </div>\n"
    "        <div class=\"proto-bar\">\n"
    "            <div class=\"proto-header\">\n"
    "                <span class=\"proto-name\">ICMP</span>\n"
    "                <span class=\"proto-count\" id=\"pICMP\">0</span>\n"
    "            </div>\n"
    "            <div class=\"proto-track\">\n"
    "                <div class=\"proto-fill fill-icmp\"\n"
    "                     id=\"bICMP\" style=\"width:0%\"></div>\n"
    "            </div>\n"
    "        </div>\n"
    "        <div class=\"proto-bar\">\n"
    "            <div class=\"proto-header\">\n"
    "                <span class=\"proto-name\">Other</span>\n"
    "                <span class=\"proto-count\" id=\"pOTHER\">0</span>\n"
    "            </div>\n"
    "            <div class=\"proto-track\">\n"
    "                <div class=\"proto-fill fill-other\"\n"
    "                     id=\"bOTHER\" style=\"width:0%\"></div>\n"
    "            </div>\n"
    "        </div>\n"
    "\n"
    "        <div class=\"panel-title\" style=\"margin-top:24px\">\n"
    "            Top Connections\n"
    "        </div>\n"
    "        <div id=\"topConns\" style=\"font-size:0.7rem;color:#64748b\">\n"
    "            Waiting for traffic...\n"
    "        </div>\n"
    "    </div>\n"
    "\n"
    "    <!-- Live packet feed -->\n"
    "    <div class=\"packet-feed\">\n"
    "        <div class=\"panel-title\">Live Packet Feed</div>\n"
    "        <div class=\"feed-header\">\n"
    "            <span>#</span>\n"
    "            <span>Proto</span>\n"
    "            <span>Source</span>\n"
    "            <span></span>\n"
    "            <span>Destination</span>\n"
    "            <span>Service</span>\n"
    "            <span style=\"text-align:right\">Bytes</span>\n"
    "        </div>\n"
    "        <div class=\"feed-scroll\" id=\"feed\"></div>\n"
    "    </div>\n"
    "\n"
    "</div>\n"
    "\n"
    "<script>\n"
    "// ── State ──────────────────────────────────────────────────────────────────\n"
    "const MAX_FEED_ROWS  = 200;\n"
    "const CHART_POINTS   = 60;\n"
    "\n"
    "let packetCount  = 0;\n"
    "let totalBytes   = 0;\n"
    "let protos       = { TCP: 0, UDP: 0, ICMP: 0, OTHER: 0 };\n"
    "let hosts        = new Set();\n"
    "let connections  = {};\n"
    "let bwHistory    = new Array(CHART_POINTS).fill(0);\n"
    "let bytesThisSec = 0;\n"
    "let pktsThisSec  = 0;\n"
    "\n"
    "// ── WebSocket ──────────────────────────────────────────────────────────────\n"
    "const dot  = document.getElementById('statusDot');\n"
    "const text = document.getElementById('statusText');\n"
    "\n"
    "function connect() {\n"
    "    const ws = new WebSocket(`ws://${location.host}`);\n"
    "\n"
    "    ws.onopen = () => {\n"
    "        dot.classList.add('connected');\n"
    "        text.textContent = 'Live';\n"
    "    };\n"
    "\n"
    "    ws.onclose = () => {\n"
    "        dot.classList.remove('connected');\n"
    "        text.textContent = 'Reconnecting...';\n"
    "        setTimeout(connect, 2000);\n"
    "    };\n"
    "\n"
    "    ws.onerror = () => {\n"
    "        text.textContent = 'Error';\n"
    "    };\n"
    "\n"
    "    ws.onmessage = (e) => {\n"
    "        const pkt = JSON.parse(e.data);\n"
    "        handlePacket(pkt);\n"
    "    };\n"
    "}\n"
    "\n"
    "// ── Packet handler ─────────────────────────────────────────────────────────\n"
    "function handlePacket(pkt) {\n"
    "    packetCount++;\n"
    "    totalBytes   += pkt.length;\n"
    "    bytesThisSec += pkt.length;\n"
    "    pktsThisSec++;\n"
    "\n"
    "    // Protocol counts\n"
    "    const p = pkt.proto in protos ? pkt.proto : 'OTHER';\n"
    "    protos[p]++;\n"
    "\n"
    "    // Unique hosts\n"
    "    hosts.add(pkt.src_ip);\n"
    "    hosts.add(pkt.dst_ip);\n"
    "\n"
    "    // Connection tracking\n"
    "    const key = `${pkt.src_ip}:${pkt.src_port}->${pkt.dst_ip}:${pkt.dst_port}`;\n"
    "    connections[key] = (connections[key] || 0) + 1;\n"
    "\n"
    "    addFeedRow(pkt);\n"
    "    updateStats();\n"
    "    updateProtoBars();\n"
    "    updateTopConns();\n"
    "}\n"
    "\n"
    "// ── Feed ───────────────────────────────────────────────────────────────────\n"
    "const feed = document.getElementById('feed');\n"
    "\n"
    "function addFeedRow(pkt) {\n"
    "    const row = document.createElement('div');\n"
    "    row.className = 'packet-row';\n"
    "\n"
    "    const protoClass = {\n"
    "        TCP: 'col-tcp', UDP: 'col-udp',\n"
    "        ICMP: 'col-icmp'\n"
    "    }[pkt.proto] || 'col-other';\n"
    "\n"
    "    const src = pkt.src_port\n"
    "        ? `${pkt.src_ip}:${pkt.src_port}`\n"
    "        : pkt.src_ip;\n"
    "    const dst = pkt.dst_port\n"
    "        ? `${pkt.dst_ip}:${pkt.dst_port}`\n"
    "        : pkt.dst_ip;\n"
    "\n"
    "    row.innerHTML = `\n"
    "        <span class=\"col-num\">${packetCount}</span>\n"
    "        <span class=\"col-proto ${protoClass}\">${pkt.proto}</span>\n"
    "        <span class=\"col-ip\">${src}</span>\n"
    "        <span class=\"col-arrow\">→</span>\n"
    "        <span class=\"col-ip\">${dst}</span>\n"
    "        <span class=\"col-svc\">${pkt.service || ''}</span>\n"
    "        <span class=\"col-bytes\">${pkt.length}b</span>\n"
    "    `;\n"
    "\n"
    "    feed.insertBefore(row, feed.firstChild);\n"
    "\n"
    "    // Keep feed bounded\n"
    "    while (feed.children.length > MAX_FEED_ROWS) {\n"
    "        feed.removeChild(feed.lastChild);\n"
    "    }\n"
    "}\n"
    "\n"
    "// ── Stats ──────────────────────────────────────────────────────────────────\n"
    "function updateStats() {\n"
    "    document.getElementById('statTotal').textContent =\n"
    "        packetCount.toLocaleString();\n"
    "    document.getElementById('statTCP').textContent =\n"
    "        protos.TCP.toLocaleString();\n"
    "    document.getElementById('statUDP').textContent =\n"
    "        protos.UDP.toLocaleString();\n"
    "    document.getElementById('statHosts').textContent =\n"
    "        hosts.size;\n"
    "}\n"
    "\n"
    "// ── Protocol bars ──────────────────────────────────────────────────────────\n"
    "function updateProtoBars() {\n"
    "    const total = Object.values(protos).reduce((a, b) => a + b, 0);\n"
    "    if (total === 0) return;\n"
    "\n"
    "    for (const [name, count] of Object.entries(protos)) {\n"
    "        const pct = ((count / total) * 100).toFixed(1);\n"
    "        const el = document.getElementById(`p${name}`);\n"
    "        const bar = document.getElementById(`b${name}`);\n"
    "        if (el) el.textContent = count.toLocaleString();\n"
    "        if (bar) bar.style.width = pct + '%';\n"
    "    }\n"
    "}\n"
    "\n"
    "// ── Top connections ────────────────────────────────────────────────────────\n"
    "function updateTopConns() {\n"
    "    const sorted = Object.entries(connections)\n"
    "        .sort((a, b) => b[1] - a[1])\n"
    "        .slice(0, 5);\n"
    "\n"
    "    const container = document.getElementById('topConns');\n"
    "    container.innerHTML = sorted.map(([key, count]) =>\n"
    "        `<div style=\"margin-bottom:6px;padding:4px;\n"
    "                     background:#0a0e1a;border-radius:3px\">\n"
    "            <div style=\"color:#94a3b8;word-break:break-all;\n"
    "                        font-size:0.65rem\">${key}</div>\n"
    "            <div style=\"color:#38bdf8;font-size:0.7rem\">\n"
    "                ${count} packets</div>\n"
    "         </div>`\n"
    "    ).join('');\n"
    "}\n"
    "\n"
    "// ── Bandwidth chart ────────────────────────────────────────────────────────\n"
    "const canvas = document.getElementById('bwChart');\n"
    "const ctx    = canvas.getContext('2d');\n"
    "\n"
    "function resizeCanvas() {\n"
    "    canvas.width  = canvas.offsetWidth;\n"
    "    canvas.height = canvas.offsetHeight;\n"
    "}\n"
    "\n"
    "function drawChart() {\n"
    "    resizeCanvas();\n"
    "    const w = canvas.width;\n"
    "    const h = canvas.height;\n"
    "\n"
    "    ctx.clearRect(0, 0, w, h);\n"
    "\n"
    "    const max = Math.max(...bwHistory, 1);\n"
    "    const step = w / (CHART_POINTS - 1);\n"
    "\n"
    "    // Grid lines\n"
    "    ctx.strokeStyle = '#1e2d3d';\n"
    "    ctx.lineWidth = 1;\n"
    "    for (let i = 0; i <= 4; i++) {\n"
    "        const y = h - (i / 4) * h;\n"
    "        ctx.beginPath();\n"
    "        ctx.moveTo(0, y);\n"
    "        ctx.lineTo(w, y);\n"
    "        ctx.stroke();\n"
    "    }\n"
    "\n"
    "    // Fill area\n"
    "    ctx.beginPath();\n"
    "    ctx.moveTo(0, h);\n"
    "    bwHistory.forEach((v, i) => {\n"
    "        const x = i * step;\n"
    "        const y = h - (v / max) * h * 0.9;\n"
    "        i === 0 ? ctx.moveTo(x, y) : ctx.lineTo(x, y);\n"
    "    });\n"
    "    ctx.lineTo(w, h);\n"
    "    ctx.closePath();\n"
    "\n"
    "    const grad = ctx.createLinearGradient(0, 0, 0, h);\n"
    "    grad.addColorStop(0, 'rgba(56,189,248,0.3)');\n"
    "    grad.addColorStop(1, 'rgba(56,189,248,0)');\n"
    "    ctx.fillStyle = grad;\n"
    "    ctx.fill();\n"
    "\n"
    "    // Line\n"
    "    ctx.beginPath();\n"
    "    ctx.strokeStyle = '#38bdf8';\n"
    "    ctx.lineWidth = 2;\n"
    "    bwHistory.forEach((v, i) => {\n"
    "        const x = i * step;\n"
    "        const y = h - (v / max) * h * 0.9;\n"
    "        i === 0 ? ctx.moveTo(x, y) : ctx.lineTo(x, y);\n"
    "    });\n"
    "    ctx.stroke();\n"
    "}\n"
    "\n"
    "// ── 1-second tick ──────────────────────────────────────────────────────────\n"
    "setInterval(() => {\n"
    "    bwHistory.push(bytesThisSec);\n"
    "    if (bwHistory.length > CHART_POINTS) bwHistory.shift();\n"
    "\n"
    "    document.getElementById('statRate').textContent =\n"
    "        pktsThisSec.toLocaleString();\n"
    "    document.getElementById('statBytes').textContent =\n"
    "        (bytesThisSec / 1024).toFixed(1);\n"
    "\n"
    "    bytesThisSec = 0;\n"
    "    pktsThisSec  = 0;\n"
    "\n"
    "    drawChart();\n"
    "}, 1000);\n"
    "\n"
    "// ── Init ───────────────────────────────────────────────────────────────────\n"
    "window.addEventListener('resize', drawChart);\n"
    "connect();\n"
    "</script>\n"
    "</body>\n"
    "</html>\n"
;
